/* Generated by Together */

package org.ensembl.mart.lib;

public class CompositeAttribute implements Attribute {
    public String getName(){
        // Write your code here
        return null;
    }
    
	public void setTableConstraint(String tableConstraint) {
		this.tableConstraint = tableConstraint;
	}

	public String getTableConstraint() {
		return tableConstraint;
	}


	private String tableConstraint; 
}
