/* Generated by Together */

package org.ensembl.mart.explorer.test;

import org.apache.log4j.*;
import junit.framework.*;
import org.ensembl.mart.explorer.*;

/**
 * Base class for tests that sets up the logging system if necessary. 
 */
public abstract class Base extends TestCase {

  	protected Engine engine = new Engine();
    protected Query query = new Query();

    public void setUp() {
	    query.setHost("kaka.sanger.ac.uk");
      query.setUser("anonymous");
      query.setDatabase( "ensembl_mart_10_1" );
      query.setSpecies( "homo_sapiens" );
      query.setFocus( "gene" );
    }

    public Base(String name) {
        super(name);
			if ( System.getProperty("log4j.configuration")==null ) {
        BasicConfigurator.configure();
        Logger.getRoot().setLevel( Level.WARN );
      }
    }

}
