/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JButton;
import org.ensembl.mart.explorer.Query;

/** Input panel where user selects export format, compression and file name. */
public class ExportPanel extends JPanel implements org.ensembl.mart.explorer.gui.QueryInputPage {
    /** Creates new form ExportPanel */
    public ExportPanel() {
        initGUI();
    }

    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(fileNamePanel);
        add(compressionPanel);
        add(exportFormatPanel);
        fileNameLabel.setText("File name");
        fileNameLabel.setToolTipText("Name of file results written to");
        fileNamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(153, 153, 153), 1), "Output File", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
            new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
        fileNamePanel.add(fileNameLabel);
        fileNamePanel.add(fileName);
        noCompressionButton.setText("jRadioButton1");
        noCompressionButton.setLabel("None");
        noCompressionButton.setSelected(true);
        compressionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(153, 153, 153), 1), "Compression", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
            new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
        compressionPanel.add(noCompressionButton);
        exportFormatPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(153, 153, 153), 1), "Format", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
            new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
        exportFormatPanel.add(textTabSeparatedFormatButton);
        textTabSeparatedFormatButton.setText("jRadioButton1");
        textTabSeparatedFormatButton.setLabel("Text, tab separated");
        textTabSeparatedFormatButton.setSelected(true);
        fileName.setEditable(true);
    }

    public void updateQuery(Query query){
        // Write your code here
    }

    public void updatePage(Query query){
        // Write your code here
    }

    private JPanel fileNamePanel = new JPanel();
    private JLabel fileNameLabel = new JLabel();
    private JComboBox fileName = new JComboBox();
    private JPanel compressionPanel = new JPanel();
    private JRadioButton noCompressionButton = new JRadioButton();
    private JPanel exportFormatPanel = new JPanel();
    private JRadioButton textTabSeparatedFormatButton = new JRadioButton();
}
