/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import javax.swing.JPanel;
import javax.swing.JCheckBox;
import org.ensembl.mart.explorer.*;

/** Input panel where user specifies what data is to be exported. */
public class IncludePanel extends JPanel implements org.ensembl.mart.explorer.gui.QueryInputPage {
    /** Creates new form OutputPanel */
    public IncludePanel() {
        initGUI();
    }

    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(ensemblGeneIDCheckBox);
        ensemblGeneIDCheckBox.setText("jCheckBox1");
        ensemblGeneIDCheckBox.setLabel("Ensembl Gene ID");
    }

    public void updateQuery(Query query) {
        if (ensemblGeneIDCheckBox.isSelected())
            query.addAttribute(ensemblGeneID);
        else
            query.removeAttribute(ensemblGeneID);
    }

    public void updatePage(Query query) {
        ensemblGeneIDCheckBox.setSelected(query.hasAttribute(ensemblGeneID));
    }

    public FieldAttribute getEnsemblGeneID() {
        return ensemblGeneID;
    }

    public void setEnsemblGeneID(FieldAttribute ensemblGeneID) {
        this.ensemblGeneID = ensemblGeneID;
    }

    private JCheckBox ensemblGeneIDCheckBox = new JCheckBox();
    private FieldAttribute ensemblGeneID = new FieldAttribute("ensembl_gene_id");
}
