/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import org.apache.log4j.*;
import java.util.*;
import javax.swing.JFrame;
import java.awt.event.WindowEvent;
import javax.swing.JTabbedPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JToolBar;
import javax.swing.JButton;
import org.ensembl.mart.explorer.*;
import java.awt.Dimension;


public class MartExplorerGUI extends JFrame {

	private final static int WIDTH = 600;
	private final static int HEIGHT = 800;


    /** Creates new form JFrame */
    public MartExplorerGUI() {
        initGUI();
        setSize( new Dimension(WIDTH, HEIGHT) );
    }


    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        logger.info("start init");
        newToolBarButton.setText("jButton1");
        newToolBarButton.setLabel("New Query");
        toolBar.add(newToolBarButton);
        toolBar.add(exportToolBarButton);
        exportToolBarButton.setText("jButton1");
        exportToolBarButton.setLabel("Export");
        exportToolBarButton.setActionCommand("export");
        resultTextArea.setText("");
        resultTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(153, 153, 153), 1), "Result", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
            new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
        addWindowListener(
            new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    exitForm(evt);
                }
            });
        setTitle("MartExplorer");
        getContentPane().getPreferredSize().setSize(new java.awt.Dimension(600, 600));
        //setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(this.getContentPane(), javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(toolBar);
        getContentPane().add(queryPanel);
        getContentPane().add(summaryPanel);
        getContentPane().add(resultTextArea);
        summaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(153, 153, 153), 1), "Summary", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
            new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
        fileMenu.setText("File");
        fileMenu.add(exitMenuItem);
        menuBar.add(fileMenu);
        menuBar.add(queryMenu);
        menuBar.add(helpMenu);
        exitMenuItem.setText("jMenuItem1");
        exitMenuItem.setActionCommand("exitMenuItem");
        exitMenuItem.setLabel("Exit");
        exitMenuItem.setToolTipText("Exits Application");
        exitMenuItem.addActionListener(
            new ActionListener() {
                public void actionPerformed(ActionEvent e) { exitMenuItemActionPerformed(e); }
            });
        helpMenu.setText("Help");
        helpMenu.add(aboutMenuItem);
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(
            new ActionListener() {
                public void actionPerformed(ActionEvent e) { aboutActionPerformed(e); }
            });
        setJMenuBar(menuBar);
        setSize(new java.awt.Dimension(500,402));
        logger.info("finished init");
        exportToolBarButton.addActionListener(
            new ActionListener() {
                public void actionPerformed(ActionEvent e) { exportToolBarButtonActionPerformed(e); }
            });
        queryMenu.setText("Query");
        queryMenu.add(kakaMenuItem);
        queryMenu.add(executeMenuItem);
        queryMenu.add(newMenuItem);
        kakaMenuItem.setText("Kaka partial query");
        executeMenuItem.setText("Execute");
        newMenuItem.setText("New");
        newMenuItem.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){newMenuItemActionPerformed(e);}});
        executeMenuItem.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){executeMenuItemActionPerformed(e);}});
        kakaMenuItem.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){kakaMenuItemActionPerformed(e);}});
        newToolBarButton.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){newToolBarButtonActionPerformed(e);}});
    }

    /** Exit the Application */
    private void exitForm(WindowEvent evt) {
        exit();
    }

    public void run() {
        logger.info("Running");
        setVisible(true);
        logger.info("visible");
    }

    public void exitMenuItemActionPerformed(ActionEvent e) {
        exit();
    }

    private void exit() {
        System.exit(0);
    }

    public void aboutActionPerformed(ActionEvent e) {
        new AboutDialog().setVisible(true);
    }

    public void exportToolBarButtonActionPerformed(ActionEvent e) {
        executeQuery();
    }

		private void newQuery() {
			logger.warn("todo");
    }

		private void executeQuery() {
			Query q = queryPanel.retrieveQuery();
      logger.warn( "Executing query: " + q );
			engine.execute( q );
    }

		private void kakaPartialQuery() {
			Query q = new Query();
      q.setHost( "kaka.sanger.ac.uk" );
      q.setUser( "anonymous" );
      logger.warn( "Initialising partial kaka query: " + q );
			queryPanel.updatePage( q );
    }

    public void newMenuItemActionPerformed(ActionEvent e) {
			newQuery();
    }


    public void executeMenuItemActionPerformed(ActionEvent e) {
			executeQuery();
    }

    public void kakaMenuItemActionPerformed(ActionEvent e) {
			kakaPartialQuery();
    }

    public void newToolBarButtonActionPerformed(ActionEvent e) {
			newQuery();
    }

    private static final Logger logger = Logger.getLogger(MartExplorerGUI.class.getName());
    private JTextArea resultTextArea = new JTextArea();
    private QueryPanel queryPanel = new QueryPanel();
    private JMenuBar menuBar = new JMenuBar();
    private JMenu fileMenu = new JMenu();
    private JMenuItem exitMenuItem = new JMenuItem();
    private JMenu helpMenu = new JMenu();
    private JMenuItem aboutMenuItem = new JMenuItem();
    private JToolBar toolBar = new JToolBar();
    private JButton newToolBarButton = new JButton();
    private JButton exportToolBarButton = new JButton();
    private SummaryPanel summaryPanel = new SummaryPanel();
    private JMenu queryMenu = new JMenu();
    private JMenuItem kakaMenuItem = new JMenuItem();
    private JMenuItem executeMenuItem = new JMenuItem();
    private JMenuItem newMenuItem = new JMenuItem();
    private Engine engine = new Engine();
}
