/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import org.ensembl.mart.explorer.Query;
public interface QueryInputPage {
    /** Copyies parameters from this input page into the query. */
    void updateQuery(Query query);

    /** Copies relevant parameters from the query into this page. */
    void updatePage(Query query);
}
