/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import java.awt.*;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import org.ensembl.mart.explorer.Query;
import org.ensembl.mart.explorer.*;

/** Panel in which user enters a query. */
public class QueryPanel extends JPanel {
    /** Creates new form QueryPanel */
    public QueryPanel( MartExplorerGUI martExplorerGUI) {
        initGUI();
        this.martExplorerGUI = martExplorerGUI;
    }

	private void clear() {
		query = new Query();

  }

    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        setPreferredSize(new Dimension(300, 200));
        setLayout(new java.awt.BorderLayout());
        add(queryTabs, java.awt.BorderLayout.CENTER);
        queryTabs.add(databaseTab, "Database");
        queryTabs.add(regionTab, "Region");
        queryTabs.add(includeTab, "Include");
        queryTabs.add(exportTab, "Export");
    }

    /** Loads a predefined query into the query panel so that the query parameters are displayed in the input pages. */
    public void updatePage( Query query) {
			for (int i=0; i<inputPages.length; i++) {
				inputPages[i].updatePage( query );
      }
    }

    /** Returns the query defined by the user. */
    public Query retrieveQuery() {
			for (int i=0; i<inputPages.length; i++) {
				inputPages[i].updateQuery( query );
      }

      return query;
    }

    public MartExplorerGUI getMartExplorerGUI(){
            return martExplorerGUI;
        }

    public void setMartExplorerGUI(MartExplorerGUI martExplorerGUI){
            this.martExplorerGUI = martExplorerGUI;
        }

    private JTabbedPane queryTabs = new JTabbedPane();
    private DatabaseConfigPage databaseTab = new DatabaseConfigPage();
    private ExportPanel exportTab = new ExportPanel( this );
    private RegionPanel regionTab = new RegionPanel();
    private IncludePanel includeTab = new IncludePanel();
    private QueryInputPage[] inputPages = new QueryInputPage[] {
			databaseTab
      ,exportTab
      ,regionTab
			,includeTab
    };
    private Query query = new Query();
    private MartExplorerGUI martExplorerGUI;
}
