/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import org.ensembl.mart.explorer.*;

/** Input options for specifying region to search. */
public class RegionPanel extends JPanel implements org.ensembl.mart.explorer.gui.QueryInputPage {
    /** Creates new form RegionTab */
    public RegionPanel() {
        initGUI();
    }

    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        entireGenomeButton.setText("Entire Genome");
        entireGenomeButton.setToolTipText("Get data for whole genome");
        chromosomePanel.setLayout(new javax.swing.BoxLayout(chromosomePanel, javax.swing.BoxLayout.X_AXIS));
        chromosomePanel.add(chromosomeButton);
        chromosomePanel.add(chromosome);
        chromosomeButton.setText("Chromosome");
        chromosomeButton.setToolTipText("Limit to this chromosome");
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(entireGenomePanel);
        add(chromosomePanel);
        entireGenomePanel.setLayout(new javax.swing.BoxLayout(entireGenomePanel, javax.swing.BoxLayout.X_AXIS));
        entireGenomePanel.add(entireGenomeButton);
        regionGroup.add(entireGenomeButton);
        regionGroup.add(chromosomeButton);
    }

    public void updateQuery(Query query){
        // Write your code here
    }

    public void updatePage(Query query){
        // Write your code here
    }

    private JPanel chromosomePanel = new JPanel();
    private JRadioButton chromosomeButton = new JRadioButton();
    private JPanel entireGenomePanel = new JPanel();
    private JRadioButton entireGenomeButton = new JRadioButton();
    private JComboBox chromosome = new JComboBox();
    private ButtonGroup regionGroup = new ButtonGroup();
}
