/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import org.ensembl.mart.explorer.*;
import javax.swing.*;


public class ResultWindow extends JFrame implements ResultTarget {


    public ResultWindow(String name, ResultRenderer renderer) {
			super(name);
      this.name = name;
      this.renderer = renderer;
    }

    public ResultRenderer getRenderer(){
            return renderer;
        }

    public void setRenderer(ResultRenderer renderer){
            this.renderer = renderer;
        }

    public String toString() {
      StringBuffer buf = new StringBuffer();

			buf.append("[");
      buf.append(" name=").append(name);
      buf.append(" ,renderer=").append(renderer);
      buf.append("]");

      return buf.toString();
    }

    public String getName(){
            return name;
        }

    public void setName(String name){
            this.name = name;
        }

    private ResultRenderer renderer;
    private String name;
}
