/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import org.apache.log4j.*;
import javax.swing.*;

public class SummaryPanel extends JPanel {
    private static final Logger logger = Logger.getLogger(SummaryPanel.class.getName());

    /** Creates new form SummaryPanel */
    public SummaryPanel() {
        initGUI();
    }

    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        //logger.info("start");
        setLayout(new java.awt.BorderLayout());
        add(summaryTable, java.awt.BorderLayout.CENTER);
    }

    private Object[] [] data = {
    	{"Start", "... start summary ...", "total"},
    	{"Region", "... region summary ...", "total"}
        };
    private String[] columnNames = {"","",""};
    private JTable summaryTable = new JTable(data, columnNames);
}
