/* Generated by Together */

package org.ensembl.mart.explorer.gui;

import javax.swing.JComboBox;
public class Tool {
    /**
     * Prepends value to the front of the list of items in the combo box.
     */
	static final void prepend( String value, JComboBox combo ) {
		combo.insertItemAt( value, 0 );
}

    /**
     * Returns the selected item, null if none selected.
     */
	static final String selected( JComboBox combo ) {
  return combo.getModel().getSelectedItem().toString();
}
}
