/* Generated by Together */

package org.ensembl.mart.explorer;

public class CompositeAttribute implements Attribute {
    public String sqlRepr(){
        // Write your code here
        return null;
    }
}
