/* Generated by Together */

package org.ensembl.mart.explorer;

import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;

/**
 * Provides input options for specifying which database to connect to. 
 */
public class DatabaseConfigPage extends JPanel {
    /** Creates new form DatabaseConfigPane */
    public DatabaseConfigPage() {
        initGUI();
    }

    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        port.setEditable(true);
        port.setToolTipText("Database port");
        passwordLabel.setText("Password");
        passwordLabel.setToolTipText("Host Name");
        passwordPanel.setLayout(new javax.swing.BoxLayout(passwordPanel,javax.swing.BoxLayout.X_AXIS));
        passwordPanel.add(passwordLabel);
        passwordPanel.add(password);
        userLabel.setText("User");
        userLabel.setToolTipText("User Name");
        userPanel.setLayout(new javax.swing.BoxLayout(userPanel,javax.swing.BoxLayout.X_AXIS));
        userPanel.add(userLabel);
        userPanel.add(user);
        portLabel.setText("Port");
        portLabel.setToolTipText("Port Number");
        portPanel.setLayout(new javax.swing.BoxLayout(portPanel,javax.swing.BoxLayout.X_AXIS));
        portPanel.add(portLabel);
        portPanel.add(port);
        hostLabel.setText("Host");
        hostLabel.setToolTipText("Host Name");
        hostPanel.setLayout(new javax.swing.BoxLayout(hostPanel,javax.swing.BoxLayout.X_AXIS));
        hostPanel.add(hostLabel);
        hostPanel.add(host);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(hostPanel);
        add(portPanel);
        add(userPanel);
        add(passwordPanel);
        host.setEditable(true);
        host.setToolTipText("Database host computer");
        user.setEditable(true);
        user.setToolTipText("Database user name");
        password.setEditable(true);
        password.setToolTipText("Database password");
    }

    private JPanel hostPanel = new JPanel();
    private JLabel hostLabel = new JLabel();
    private JPanel portPanel = new JPanel();
    private JLabel portLabel = new JLabel();
    private JPanel userPanel = new JPanel();
    private JLabel userLabel = new JLabel();
    private JPanel passwordPanel = new JPanel();
    private JLabel passwordLabel = new JLabel();
    private JComboBox host = new JComboBox();
    private JComboBox port = new JComboBox();
    private JComboBox user = new JComboBox();
    private JComboBox password = new JComboBox();
}
