/* Generated by Together */

/*
    Copyright (C) 2003 EBI, GRL

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
 */
package org.ensembl.mart.explorer;

/**
 * Holds the name of a single field attribute for inclusion in a query.
 * Implements hashCode() and equals() for simple retrieval from Collections.
 * 
 * @author <a href="mailto:craig@ebi.ac.uk">Craig Melsopp</a>
 * @author <a href="maito:dlondon@ebi.ac.uk">Darin London</a>
 */
public class FieldAttribute implements Attribute {
	/**
	 * constructs a FieldAttribute with the given field name
	 * 
	 * @param field - String name of attribute to retrieve (roughly
	 * corresponds to a field of a table in the mart database).
	 */
    public FieldAttribute(String field) {
      this.field = field;
    }
    
    public int hashCode() {
    		int result = 17;
    		result = 37*result + ((field == null) ? 0 : field.hashCode()); 
				result = 37*result + ((tableConstraint == null) ? 0 : tableConstraint.hashCode()); 
        return result;
    }

    public boolean equals(Object obj) {
        return hashCode() == obj.hashCode() && obj instanceof FieldAttribute;
    }

    /**
     * returns a description of the attribute, for use by logging systems
     * 
     * @return String attribute description (field=field)
     */
    public String toString() {
      StringBuffer buf = new StringBuffer();

			buf.append("[");
      buf.append(" field=").append(field);
      buf.append(" ]");

      return buf.toString();
    }

    /**
     * returns the field name
     * 
     * @return String field
     */
    public String getName(){
			return field;
    }

		public void setTableConstraint(String tableConstraint) {
			this.tableConstraint = tableConstraint;
		}

		public String getTableConstraint() {
			return tableConstraint;
		}


		private String tableConstraint;
    private String field;
}
