/* Generated by Together */

package org.ensembl.mart.explorer;

public interface Filter {
    String getType();

    /**
     * Value, null if not needed. This can be added to the prepared statment.
     */
    String getValue();

    /**
     * String to be included in where clause.
     */
    String getWhereClause();
}
