/* Generated by Together */

package org.ensembl.mart.explorer;
import java.rmi.RemoteException;

/**
 * Signals that a problem has occured in MartExplorer code. 
 */
public class FormatException extends RemoteException {
    public FormatException() {
      super();
    }

    public FormatException(String message) {
      super( message );
    }

    public FormatException(String message, Exception exception) {
      super( message, exception );
    }

    public FormatException(Exception exception) {
      super( exception.getMessage(), exception );
    }
}
