/* Generated by Together */

package org.ensembl.mart.explorer;

import java.sql.*;

public interface Formatter {
    void setResultSet(ResultSet resultSet);

		String readLine() throws SQLException;
}
