/* Generated by Together */

package org.ensembl.mart.explorer;
import java.rmi.RemoteException;

/**
 * Signals that a problem has occured in MartExplorer code. 
 */
public class FormatterException extends RemoteException {
    public FormatterException() {
      super();
    }

    public FormatterException(String message) {
      super( message );
    }

    public FormatterException(String message, Exception exception) {
      super( message, exception );
    }

    public FormatterException(Exception exception) {
      super( exception.getMessage(), exception );
    }
}
