/* Generated by Together */

package org.ensembl.mart.explorer;
import java.rmi.RemoteException;

/**
 * Signals that a problem has occured in MartExplorer code. 
 */
public class InvalidQueryException extends RemoteException {
    public InvalidQueryException() {
      super();
    }

    public InvalidQueryException(String message) {
      super( message );
    }

    public InvalidQueryException(String message, Exception exception) {
      super( message, exception );
    }

    public InvalidQueryException(Exception exception) {
      super( exception.getMessage(), exception );
    }
}
