/* Generated by Together */

package org.ensembl.mart.explorer;

public class IsNullFilter implements Filter {
    public String getType(){ return type; }

    public void setType(String type){ this.type = type; }

    public String getWhereClause() {
      return type + " is null ";
    }

  public String getRightHandClause() {
    return " is null ";
  }

	public String getValue() {
		return null;
}

    private String type;
}
