/* Generated by Together */

package org.ensembl.mart.explorer;

import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 * Panel in which user enters a query. 
 */
public class QueryPanel extends JPanel {
    /** Creates new form QueryPanel */
    public QueryPanel() {
        initGUI();
    }

    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        setLayout(new java.awt.BorderLayout());
        add(queryTabs, java.awt.BorderLayout.CENTER);
        queryTabs.add(databaseTab, "Database");
        queryTabs.add(regionTab, "Region");
        queryTabs.add(exportTab, "Export");
    }

    private JTabbedPane queryTabs = new JTabbedPane();
    private JPanel databaseTab = new JPanel();
    private JPanel exportTab = new JPanel();
    private JPanel regionTab = new JPanel();
}
