/* Generated by Together */

package org.ensembl.mart.explorer;

public class ResultFile implements ResultTarget {
	public ResultFile(String fileName, ResultRenderer renderer) {
  	this.name = fileName;
    this.renderer = renderer;
  }

    public String getName() {
        return name;
    }

    public void setName(String fileName) {
        this.name = fileName;
    }

    public ResultRenderer getRenderer() {
        return renderer;
    }

    public void setRenderer(ResultRenderer renderer) {
        this.renderer = renderer;
    }

    public boolean isZipCompreesion(){
            return zipCompreesion;
        }

    public void setZipCompreesion(boolean zipCompreesion){
            this.zipCompreesion = zipCompreesion;
        }

    public boolean isGzipCompression(){
            return gzipCompression;
        }

    public void setGzipCompression(boolean gzipCompression){
            this.gzipCompression = gzipCompression;
        }


    public String toString() {
      StringBuffer buf = new StringBuffer();

			buf.append("[");
      buf.append(" name=").append(name);
      buf.append(" ,renderer=").append(renderer);
      buf.append(" ,zipCompreesion=").append(zipCompreesion);
      buf.append(" ,gzipCompression=").append(gzipCompression);
      buf.append("]");

      return buf.toString();
    }

    private String name;
    private ResultRenderer renderer;
    private boolean zipCompreesion;
    private boolean gzipCompression;
}
