/* Generated by Together */

package org.ensembl.mart.explorer;
import java.sql.ResultSet;

public interface ResultTarget {
    Formatter getFormatter();

    void setFormatter(Formatter formatter);

    void setName(String fileName);

    String getName();

    void output(ResultSet rs)  throws FormatterException ;
}
