/* Generated by Together */

package org.ensembl.mart.explorer;

public interface ResultTarget {
    ResultRenderer getRenderer();

    void setRenderer(ResultRenderer renderer);

    void setName(String fileName);

    String getName();
}
