/* Generated by Together */

package org.ensembl.mart.explorer;

import java.sql.*;
import org.apache.log4j.*;

public class SeparatedValueFormatter implements Formatter {

	private final static Logger logger = Logger.getLogger( SeparatedValueFormatter.class.getName() );

    public SeparatedValueFormatter(String separator) {
        this.separator = separator;
    }

    /** @return next formatted line of result set ending with '\n', or null if no more lines. */
    public String readLine() throws SQLException {

        if ( resultSet == null) return null;
        if ( !resultSet.next() ) return null;

        if (nColumns == -1)
            nColumns = resultSet.getMetaData().getColumnCount();
        buffer.delete(0, buffer.length());
        for (int i = 1; i <= nColumns; ++i) {
            buffer.append(resultSet.getString(i));
            if (i + 1 <= nColumns) buffer.append(separator);
        }
        buffer.append("\n");
        return buffer.toString();
    }

    public String getSeparator() {
        return separator;
    }

    public void setResultSet(ResultSet resultSet) {
        this.resultSet = resultSet;
        nColumns = -1;
    }

    private String separator;
    private ResultSet resultSet;
    private int nColumns;
    private StringBuffer buffer = new StringBuffer();
}
