/* Generated by Together */

package org.ensembl.mart.explorer;

public class SequenceAttribute implements Attribute {

  /**
   * No sequence type is set.
   */
		public final static SequenceType SEQUENCE_NOT_SET = new SequenceType();
    /**
     * Concatenation of coding sequence from all exons.
     */
    public final static SequenceType TRANSCRIPT_DNA = new SequenceType();

    /**
     * Concatenation of sequence from all exons including UTRs.
     */
    public final static SequenceType CDNA = new SequenceType();

    /**
     * Peptide sequence.
     */
    public final static SequenceType PEPTIDE = new SequenceType();

    /**
     * Sequence from start of first exon in "first" transcript to end of last
     * in "last" transcript exon.
     */
    public final static SequenceType GENE_DNA = new SequenceType();

    public String getName(){
        // Write your code here
        return null;
    }

    public int getProperty(){
            return property;
        }

    public void setProperty(int property){
            this.property = property;
        }

    public SequenceType getSequenceType(){ return sequenceType; }

    public void setSequenceType(SequenceType sequenceType){ this.sequenceType = sequenceType; }

    public int getThreePrimeFlankingLength(){
            return threePrimeFlankingLength;
        }

    public void setThreePrimeFlankingLength(int threePrimeFlankingLength){
            this.fivePrimeFlankingLength = threePrimeFlankingLength;
        }

    public int getFivePrimeFlankingLength(){
            return fivePrimeFlankingLength;
        }

    public void setFivePrimeFlankingLength(int fivePrimeFlankingLength){
            this.fivePrimeFlankingLength = fivePrimeFlankingLength;
        }


    private int property;
    private SequenceType sequenceType = SEQUENCE_NOT_SET;
    private int threePrimeFlankingLength = 0;
    private int fivePrimeFlankingLength = 0;

    private static class SequenceType {
        private SequenceType() {
        }
    }
}
