/* Generated by Together */

package org.ensembl.mart.explorer;

import org.apache.log4j.*;
import java.util.*;
import javax.swing.JFrame;
import java.awt.event.WindowEvent;
import javax.swing.JTabbedPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;

public class SwingFrontEnd extends JFrame {
    /** Creates new form JFrame */
    public SwingFrontEnd() {
        initGUI();
        pack();
    }

  public SwingFrontEnd(Engine engine,
                       String host,
                       String port,
                       String user,
                       String password) {
    this();
    logger.info("Constructor:");


  }

    /** This method is called from within the constructor to initialize the form. */
    private void initGUI() {
        resultTextArea.setText("");
        resultTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(153, 153, 153), 1), "Result", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
        addWindowListener(
            new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    exitForm(evt);
                }
            });
        setTitle("MartExplorer");
        getContentPane().setLayout(
        new javax.swing.BoxLayout(this.getContentPane(), javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(queryPanel);
        getContentPane().add(summaryPanel);
        getContentPane().add(resultTextArea);
        summaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(153, 153, 153), 1), "Summary", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
    }

    /** Exit the Application */
    private void exitForm(WindowEvent evt) {
        System.exit(0);
    }

    public void run() {
      logger.info("Running");
      setVisible( true );
    }

    private Logger logger = Logger.getLogger( SwingFrontEnd.class.getName() );
    private JTextArea resultTextArea = new JTextArea();
    private JPanel summaryPanel = new JPanel();
    private QueryPanel queryPanel = new QueryPanel();
}
