/* Generated by Together */

package org.ensembl.mart.explorer;

import java.io.Reader;
import java.sql.ResultSet;

public class TSVRenderer implements ResultRenderer {
    public Reader render(ResultSet rs){
        // Write your code here
        return null;
    }
}
