/* Generated by Together */

package org.ensembl.mart.lib.test;

import java.net.URL;
import java.sql.Connection;
import java.util.Properties;

import junit.framework.TestCase;

import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.ensembl.driver.ConfigurationException;
import org.ensembl.driver.Driver;
import org.ensembl.driver.DriverManager;
import org.ensembl.mart.lib.Engine;
import org.ensembl.mart.lib.Query;

/**
 * Base class for tests that sets up the logging system if necessary. 
 */
public abstract class Base extends TestCase {

	private final static Logger logger = Logger.getLogger(Base.class.getClass());
	private final static String connprops = "data/testconnection.conf";
	private final static String connpropsEnsj = "data/testconnection_ensj.conf";

	private String dbURL = null;
	private String user = null;
	private String password = null;
	private Properties p = new Properties();
	private URL connectionconf;

	protected Driver ensjDriver = null;
	protected Engine engine;
	protected Query genequery = new Query();
	protected Query snpquery = new Query();

	public void init() {
		connectionconf = org.apache.log4j.helpers.Loader.getResource(connprops);

		if (connectionconf != null) {
			try {
				p.load(connectionconf.openStream());

				dbURL = p.getProperty("dburl");
				user = p.getProperty("mysqluser");
				password = p.getProperty("mysqlpass");
			} catch (java.io.IOException e) {
				System.out.println(
					"Caught IOException when trying to open connection configuration file " + connprops + "\n" + e + "\n\nusing default connection parameters");
			}
		} else {
			System.out.println("Failed to find connection configuration file " + connprops + " using default connection parameters");

			dbURL = "jdbc://mysql/kaka.sanger.ac.uk/ensembl_mart_11_1";
			user = "anonymous";
		}

		try {
			ensjDriver = DriverManager.load(connpropsEnsj);
		} catch (ConfigurationException e) {
			logger.warn("", e);
		}

	}

	public void setUp() {
		init();

		engine = new Engine();
    engine.setConnectionString(dbURL);
    engine.setUser(user);
    engine.setPassword(password);
		genequery.setStarBases(new String[] { "hsapiens_ensemblgene", "hsapiens_ensembltranscript" });
		genequery.setPrimaryKeys(new String[] { "gene_id", "transcript_id" });
		snpquery.setStarBases(new String[] { "hsapiens_snp" });
		snpquery.setPrimaryKeys(new String[] { "snp_id" });
	}

	public Base(String name) {
		super(name);
		if (System.getProperty("log4j.configuration") == null) {
			BasicConfigurator.configure();
			Logger.getRoot().setLevel(Level.WARN);
		}
	}

  public Connection getDBConnection() throws Exception {

		Class.forName("org.gjt.mm.mysql.Driver").newInstance();
		logger.info( dbURL );
    		
		return java.sql.DriverManager.getConnection(dbURL, user, password );
  }
}
